/*
 *  GPL LICENSE SUMMARY
 *
 *  Copyright(c) 2009-2010 Intel Corporation. All rights reserved.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of version 2 of the GNU General Public License as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful, but
 *  WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 *  General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St - Fifth Floor, Boston, MA 02110-1301 USA.
 *  The full GNU General Public License is included in this distribution
 *  in the file called LICENSE.GPL.
 *
 *  Contact Information:
 *    Intel Corporation
 *    2200 Mission College Blvd.
 *    Santa Clara, CA  97052
 *
 */

#ifndef CREPEHAL
#define CREPEHAL


// Debug hook to allow using the test app with no hardware present
//#define DEBUG_WITH_NO_HARDWARE   0x1

//Memory Map

// BASE ADDRESSES
// Hook to adjust addresses based on fpga
#define  FPGA  1
#ifdef FPGA
#define DOC_PHY_REGISTER_BASE_ADDRESS           0xf2000000
#define DOC_DS_MAC_REGISTER_BASE_ADDRESS        0xf0020000
#define DOC_US_MAC_REGISTER_BASE_ADDRESS        0xf0028000
#define DOC_ARM_REGISTER_BASE_ADDRESS           0xf3f80000
#define DMA_REGISTER_BASE_ADDRESS               0xf0030000
//#define DMA_DOCSIS_REGISTER_BASE_ADDRESS        DMA_REGISTER_BASE_ADDRESS
//Changed for naming convention
#define DOC_DMA_REGISTER_BASE_ADDRESS       (DMA_REGISTER_BASE_ADDRESS)
#define DMA_MOCA_REGISTER_BASE_ADDRESS      (DMA_REGISTER_BASE_ADDRESS + 0x400)
#define I2C_REGISTER_BASE_ADDRESS               0xf3ff0800
//I2C changed as INT
#define DOC_INT_REGISTER_BASE_ADDRESS           0xf3ff0800
#define UART_REGISTER_BASE_ADDRESS              0xf3ff0c00
#define RGMII0_REGISTER_BASE_ADDRESS            0xf3ff0d00
#define RGMII1_REGISTER_BASE_ADDRESS            0xf3ff0e00
#define GPIO_REGISTER_BASE_ADDRESS              0xf3ff0f00
#define ADDR_XLAT_REGISTER_BASE_ADDRESS         0xf3ff1000
#define EXP_BUS_REGISTER_BASE_ADDRESS           0xf3ff1100
#define MOCA_PHY_REGISTER_BASE_ADDRESS          0xf4000000
#define MOCA_MAC_REGISTER_BASE_ADDRESS          0xf4020000
#define MOCA_ARM_REGISTER_BASE_ADDRESS          0xf7f80000
#define TEST_BUFFER_BASE_ADDRESS   0x8000D000
#define TEST_BUFFER_SIZE    4096
#define NUMBER_OF_TEST_BUFFER   1024
#else
#define MAC_REGISTER_BASE_ADDRESS  0x000
#define TEST_BUFFER_BASE_ADDRESS   0x000
#endif

// REGISTER ADDRESSES
// DMA

#if 0
#define NUMBER_OF_DMA_CONTEXT             19

#define DMA_REGISTER_BASE                 DMA_REGISTER_BASE_ADDRESS
#define DMA_REGISTER_BLOCK_SIZE           0x20
#define DMA_NEXT_DESC_REGISTER_OFFSET     0x0
#define DMA_START_ADDR_REGISTER_OFFSET    0x4
#define DMA_PARAMETERS_REGISTER_OFFSET    0x8
#define DMA_MODE_CTRL_REGISTER_OFFSET     0xc
#define DMA_CURR_DESCR_REGISTER_OFFSET    0x10
#define DMA_CONTEXT_DONE_BIT              0x80000000
#define DMA_CONTEXT_REGISTER_MODE_BIT     0x40000000
#define DMA_DESCRIPTOR_MODE_BIT           0x20000000
#define DMA_HOLD_BIT                      0x10000000
#define DMA_GENERATE_EOP_BIT              0x08000000
#define DMA_LAST_DESCRIPTOR_BIT           0x02000000
#define DMA_DESCR_WBACK_BIT               0x01000000
#define DMA_IRQ_EN_BIT                    0x00800000
#define DMA_IRQ_ON_PROT_ERR_EN_BIT        0x00200000
#define DMA_IRQ_ON_AXI_ERR_EN_BIT         0x00100000
#define DMA_IRQ_BIT                       0x00080000
#define DMA_PROT_ERR_BIT                  0x00020000
#define DMA_AXI_ERR_BIT                   0x00010000
#define DMA_WORDS_TRANSFERRED_MASK        0x0000FFFF
#define DMA_BLACKOUT_MASK                 0xFF000000
#define DMA_BLACKOUT_SHIFT                24
#define DMA_BURST_LENGTH_MASK             0x000F0000
#define DMA_BURST_LENGTH_SHIFT            16
#define DMA_BLOCK_LENGTH_MASK             0x0000FFFF
#endif



// Below is mapping as of 072008 --- MoCa and  DOCSIS are mixed
//MoCa RGMII Port0 Transmit
#define DMA_WCONTEXT00_START_ADDR_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x00 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT00_NEXT_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x00 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT00_PARAMETERS_REGISTER   \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x00 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT00_MODE_CTRL_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x00 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT00_CURR_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x00 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS RGMII Port0 Transmit
#define DMA_WCONTEXT01_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x20 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT01_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x20 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT01_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x20 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT01_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x20 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT01_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x20 + DMA_CURR_DESCR_REGISTER_OFFSET)
//MoCa RGMII Port0 Receive
#define DMA_RCONTEXT02_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x40 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT02_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x40 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT02_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x40 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT02_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x40 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT02_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x40 + DMA_CURR_DESCR_REGISTER_OFFSET)
// DOCSIS RGMII Port0 Receive
#define DMA_RCONTEXT03_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x60 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT03_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x60 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT03_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x60 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT03_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x60 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT03_CURR_DESC_REGISTER   \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x60 + DMA_CURR_DESCR_REGISTER_OFFSET)
//MoCa RGMII Port1 Transmit
#define DMA_WCONTEXT04_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT04_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT04_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT04_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT04_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS RGMII Port1 Transmit
#define DMA_WCONTEXT05_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT05_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT05_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT05_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT05_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//Moca RGMII Port1 Receive
#define DMA_RCONTEXT06_START_ADDR_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT06_NEXT_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT06_PARAMETERS_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT06_MODE_CTRL_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT06_CURR_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS RGMII Port1 Receive
#define DMA_RCONTEXT07_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT07_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT07_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT07_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT07_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Upstream0
#define DMA_RCONTEXT08_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT08_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT08_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT08_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT08_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x80 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Upstream1
#define DMA_RCONTEXT09_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT09_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT09_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT09_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT09_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xa0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Upstream2
#define DMA_RCONTEXT10_START_ADDR_REGISTER    \
(DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT10_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT10_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT10_MODE_CTRL_REGISTER    \
(DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT10_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xc0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Upstream3
#define DMA_RCONTEXT11_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT11_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT11_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT11_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT11_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0xe0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Downstream Data
#define DMA_WCONTEXT12_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x100 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT12_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x100 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT12_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x100 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT12_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x100 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT12_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x100 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Downstream Command
#define DMA_WCONTEXT13_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x120 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT13_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x120 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT13_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x120 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT13_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x120 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT13_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x120 + DMA_CURR_DESCR_REGISTER_OFFSET)
//MoCa Transmit
#define DMA_RCONTEXT14_START_ADDR_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1c0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT14_NEXT_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1c0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT14_PARAMETERS_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1c0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT14_MODE_CTRL_REGISTER   \
(DOC_DMA_REGISTER_BASE_ADDRESS + 0x1c0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT14_CURR_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1c0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//MoCa Receive Data
#define DMA_WCONTEXT15_START_ADDR_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1e0 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT15_NEXT_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1e0 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT15_PARAMETERS_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1e0 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT15_MODE_CTRL_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1e0 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT15_CURR_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x1e0 + DMA_CURR_DESCR_REGISTER_OFFSET)
//MoCa Receive Command
#define DMA_RCONTEXT16_START_ADDR_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x200 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT16_NEXT_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x200 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT16_PARAMETERS_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x200 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT16_MODE_CTRL_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x200 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT16_CURR_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x200 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Mem2Mem Read
#define DMA_RCONTEXT17_START_ADDR_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x220 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_RCONTEXT17_NEXT_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x220 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_RCONTEXT17_PARAMETERS_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x220 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_RCONTEXT17_MODE_CTRL_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x220 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_RCONTEXT17_CURR_DESC_REGISTER    \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x220 + DMA_CURR_DESCR_REGISTER_OFFSET)
//DOCSIS Mem2Mem Write
#define DMA_WCONTEXT18_START_ADDR_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x240 + DMA_START_ADDR_REGISTER_OFFSET)
#define DMA_WCONTEXT18_NEXT_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x240 + DMA_NEXT_DESC_REGISTER_OFFSET)
#define DMA_WCONTEXT18_PARAMETERS_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x240 + DMA_PARAMETERS_REGISTER_OFFSET)
#define DMA_WCONTEXT18_MODE_CTRL_REGISTER   \
 (DOC_DMA_REGISTER_BASE_ADDRESS + 0x240 + DMA_MODE_CTRL_REGISTER_OFFSET)
#define DMA_WCONTEXT18_CURR_DESC_REGISTER   \
  (DOC_DMA_REGISTER_BASE_ADDRESS + 0x240 + DMA_CURR_DESCR_REGISTER_OFFSET)



//DOCSIS DS mini-MAC
#define DOCSIS_DS_IRQ_EN_REGISTER        \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x10)
#define DOCSIS_DS_IRQ_STS_REGISTER      \
       (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x14)
#define DOCSIS_TS_MAP_REGISTER           \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x18)
#define DOCSIS_TS_FORMAT_REGISTER       \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x20)
#define DOCSIS_TS_STATUS_REGISTER       \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x24)
#define DOCSIS_DS_DMA_ASSOC_REGISTER        \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x40)
#define DOCSIS_CAP_CTRL_REGISTER           \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x80)
#define DOCSIS_CAP_READ_REGISTER            \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x84)
#define DOCSIS_DS_MSG_STS_REGISTER         \
    (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x100)
#define DOCSIS_DCSD_DCS_TEST_0_REGISTER    \
    (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x180)
#define DOCSIS_DOCSIS_TEST_FIFO_0_BASE_ADDRESS  \
     (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x4000)
#define DOCSIS_TEST_FIFO_SIZE                   0x7FF
#define DOCSIS_TS_TEST_FIFO_0_BASE_ADDRESS       \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x2000)
#define DOCSIS_TS_TEST_FIFO_1_BASE_ADDRESS      \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x2100)
#define DOCSIS_TS_TEST_FIFO_2_BASE_ADDRESS       \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x2200)
#define DOCSIS_TS_TEST_FIFO_3_BASE_ADDRESS      \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x2300)
#define DOCSIS_DCSD_TS_TEST_REGISTER            \
    (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x190)
#define DOCSIS_DSMACIPADDRFLTREHN0_REGISTER      \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x200)
#define DOCSIS_DSMACIPADDRFLTREGN1_REGISTER      \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x204)
#define DOCSIS_MAC_DSID_REGISTER         \
     (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x210)
#define DOCSIS_CURR_DSID_REGISTER       \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x214)
#define DOCSIS_BPI_CTRL_REGISTER         \
     (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x300)
#define DOCSIS_BPI_INFO_REGISTER (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x304)
#define DOCSIS_SAID_0_REGISTER    (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x340)
#define DOCSIS_SAID_1_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x344)
#define DOCSIS_SAID_2_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x348)
#define DOCSIS_SAID_3_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x34c)
#define DOCSIS_SAID_4_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x350)
#define DOCSIS_SAID_5_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x354)
#define DOCSIS_SAID_6_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x358)
#define DOCSIS_SAID_7_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x35c)
#define DOCSIS_SAID_8_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x360)
#define DOCSIS_SAID_9_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x364)
#define DOCSIS_SAID_10_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x368)
#define DOCSIS_SAID_11_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x36c)
#define DOCSIS_SAID_12_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x370)
#define DOCSIS_SAID_13_REGISTER   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x374)
#define DOCSIS_SAID_14_REGISTER    (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x378)
#define DOCSIS_SAID_15_REGISTER     (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x37c)
#define DOCSIS_DSDSIDREG_L_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x400)
#define DOCSIS_DSDSIDREG_H_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x404)
#define DSIDREG_SIZE                0x8
#define DOCSIS_NUMBER_OF_DSIDREG           128
#define DOCSIS_BPI_KEY_X_0_EVEN_BASE_ADDRESS  \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x800)
#define DOCSIS_BPI_KEY_X_1_EVEN_BASE_ADDRESS   \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x804)
#define DOCSIS_BPI_KEY_X_2_EVEN_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x808)
#define DOCSIS_BPI_KEY_X_3_EVEN_BASE_ADDRESS   \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x80C)
#define DOCSIS_BPI_IV_X_0_EVEN_BASE_ADDRESS   \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x810)
#define DOCSIS_BPI_IV_X_1_EVEN_BASE_ADDRESS   \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x814)
#define DOCSIS_BPI_IV_X_2_EVEN_BASE_ADDRESS   \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x818)
#define DOCSIS_BPI_IV_X_3_EVEN_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x81C)
#define DOCSIS_BPI_KEY_X_0_ODD_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x820)
#define DOCSIS_BPI_KEY_X_1_ODD_BASE_ADDRESS   \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x824)
#define DOCSIS_BPI_KEY_X_2_ODD_BASE_ADDRESS  \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x828)
#define DOCSIS_BPI_KEY_X_3_ODD_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x82C)
#define DOCSIS_BPI_IV_X_0_ODD_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x830)
#define DOCSIS_BPI_IV_X_1_ODD_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x834)
#define DOCSIS_BPI_IV_X_2_ODD_BASE_ADDRESS    \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x838)
#define DOCSIS_BPI_IV_X_3_ODD_BASE_ADDRESS   \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x83C)
#define DOCSIS_NUMBER_BPI_KEY_IV                16
#define DOCSIS_BPI_KEY_IV_SIZE                  0x40
#define DOCSIS_DSDISCONTINUITYTS_REGISTER      \
      (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1000)
#define DOCSIS_USDISCONTINUITYTS_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1004)
#define DOCSIS_QOS_TIME_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1008)
#define DOCSIS_SYS_UP_TIME_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x100c)
#define DOCSIS_IFINOCTETS0_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1100)
#define DOCSIS_IFINUCASTPKTS0_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1104)
#define DOCSIS_IFINMULTICASTPKTS0_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1108)
#define DOCSIS_IFINBROADCASTPKTS0_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x110c)
#define DOCSIS_IFINDISCARDS0_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1110)
#define DOCSIS_IFINUNKNOWNPROTOS0_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1114)
#define DOCSIS_MPEGNFRAMES0_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x111c)
#define DOCSIS_DOCSIFSIGQUNERROREDS0_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1120)
#define DOCSIS_DOCSIFSIGQCORRECTEDS0_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1124)
#define DOCSIS_DOCSIFSIGQUNCORRECTABLES0_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1128)
#define DOCSIS_PHYTOTALRSUNCORRECTABLE0_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x112c)
#define DOCSIS_IFOUTOCTETS0_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1138)
#define DOCSIS_IFOUTDISCARDS0_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x113c)
#define DOCSIS_IFINOCTETS1_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1140)
#define DOCSIS_IFINUCASTPKTS1_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1144)
#define DOCSIS_IFINMULTICASTPKTS1_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1148)
#define DOCSIS_IFINBROADCASTPKTS1_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x114c)
#define DOCSIS_IFINDISCARDS1_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1150)
#define DOCSIS_IFINUNKNOWNPROTOS1_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1154)
#define DOCSIS_MPEGNFRAMES1_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x115c)
#define DOCSIS_DOCSIFSIGQUNERROREDS1_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1160)
#define DOCSIS_DOCSIFSIGQCORRECTEDS1_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1164)
#define DOCSIS_DOCSIFSIGQUNCORRECTABLES1_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1168)
#define DOCSIS_PHYTOTALRSUNCORRECTABLE1_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x116c)
#define DOCSIS_IFOUTOCTETS1_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1178)
#define DOCSIS_IFOUTDISCARDS1_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x117c)
#define DOCSIS_IFINOCTETS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1180)
#define DOCSIS_IFINUCASTPKTS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1184)
#define DOCSIS_IFINMULTICASTPKTS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1188)
#define DOCSIS_IFINBROADCASTPKTS2_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x118c)
#define DOCSIS_IFINDISCARDS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1190)
#define DOCSIS_IFINUNKNOWNPROTOS2_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x1194)
#define DOCSIS_MPEGNFRAMES2_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x119c)
#define DOCSIS_DOCSIFSIGQUNERROREDS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11a0)
#define DOCSIS_DOCSIFSIGQCORRECTEDS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11a4)
#define DOCSIS_DOCSIFSIGQUNCORRECTABLES2_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11a8)
#define DOCSIS_PHYTOTALRSUNCORRECTABLE2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11ac)
#define DOCSIS_IFOUTOCTETS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11b8)
#define DOCSIS_IFOUTDISCARDS2_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11bc)
#define DOCSIS_IFINOCTETS3_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11c0)
#define DOCSIS_IFINUCASTPKTS3_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11c4)
#define DOCSIS_IFINMULTICASTPKTS3_REGISTER            \
(DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11c8)
#define DOCSIS_IFINBROADCASTPKTS3_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11cc)
#define DOCSIS_IFINDISCARDS3_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11d0)
#define DOCSIS_IFINUNKNOWNPROTOS3_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11d4)
#define DOCSIS_MPEGNFRAMES3_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11dc)
#define DOCSIS_DOCSIFSIGQUNERROREDS3_REGISTER         \
   (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11e0)
#define DOCSIS_DOCSIFSIGQCORRECTEDS3_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11e4)
#define DOCSIS_DOCSIFSIGQUNCORRECTABLES3_REGISTER        \
    (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11e8)
#define DOCSIS_PHYTOTALRSUNCORRECTABLE3_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11ec)
#define DOCSIS_IFOUTOCTETS3_REGISTER           \
 (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11f8)
#define DOCSIS_IFOUTDISCARDS3_REGISTER          \
  (DOC_DS_MAC_REGISTER_BASE_ADDRESS + 0x11fc)
//DOCSIS Upstream mini-MAC
#define DOCSIS_US_CFG_REGISTER        (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x0)
#define DOCSIS_US_CFG_FIFO_MODE_SET             0x4000
#define DOCSIS_US_TEK000_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x20)
#define DOCSIS_US_TEK001_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x24)
#define DOCSIS_US_TEK002_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x28)
#define DOCSIS_US_TEK003_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x2c)
#define DOCSIS_US_TEK100_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x40)
#define DOCSIS_US_TEK101_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x44)
#define DOCSIS_US_TEK102_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x48)
#define DOCSIS_US_TEK103_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x4c)
#define DOCSIS_US_IV000_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x60)
#define DOCSIS_US_IV001_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x64)
#define DOCSIS_US_IV002_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x68)
#define DOCSIS_US_IV003_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x6c)
#define DOCSIS_US_IV100_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x80)
#define DOCSIS_US_IV101_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x84)
#define DOCSIS_US_IV102_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x88)
#define DOCSIS_US_IV103_REGISTER    (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x8c)
#define DOCSIS_US_ENC_LOC_REGISTER (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x90)
#define DOCSIS_US_INFO_REGISTER     (DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x100)

#define DOCSIS_US_PKT_FIFO_0_REGISTER \
(DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x120)
#define DOCSIS_US_PKT_FIFO_1_REGISTER \
(DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x124)
#define DOCSIS_US_PKT_FIFO_2_REGISTER \
(DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x128)
#define DOCSIS_US_PKT_FIFO_3_REGISTER \
(DOC_US_MAC_REGISTER_BASE_ADDRESS + 0x12c)






//PHY Registers
#define PHY_ADDR_MASK     0x7FFFF;  // Currently only 256*4*4 allowed
#define FFE_FBE_BUFFER_SIZE    0x18
#define FBE_START              0x10
#define  FFE_FBE_INDEX         0x2cc
#define  FFE_FBE_RD_REG        0x2d0
#define  CENTER_TAP_REGISTER   0x84
#define  FFE_FBE_CTRL          0x94
#define  FFE_NUMBER_OF_COEFF   16
#define  FBE_NUMBER_OF_COEFF   8

// MAC REGISTER OFFSETS

#define MAC_REG_DS_TEST_SEL             0x0
#define MAC_REG_DS_TEST_WR              0x1
#define MAC_REG_US_TEST_0               0x1
#define MAC_REG_US_TEST_1               0x1
#define MAC_REG_US_TEST_2               0x1
#define MAC_REG_US_TEST_3               0x1

// DS_TEST_SEL Regsiter Setting Values
#define DS_FIFO_TS_0_ENABLE             0x0
#define DS_FIFO_TS_1_ENABLE             0x1
#define DS_FIFO_TS_2_ENABLE             0x2
#define DS_FIFO_TS_3_ENABLE             0x3
#define DS_FIFO_TS_4_ENABLE             0x4
#define DS_FIFO_TS_5_ENABLE             0x5
#define DS_FIFO_OC_ENABLE               0x8
#define DS_FIFO_DOCSIS_0_ENABLE         0x10
#define DS_FIFO_DOCSIS_1_ENABLE         0x11
#define DS_FIFO_DOCSIS_2_ENABLE         0x12
#define DS_FIFO_DOCSIS_3_ENABLE         0x13
#define US_FIFO_0_ENABLE                0x10
#define US_FIFO_1_ENABLE                0x11
#define US_FIFO_2_ENABLE                0x12
#define US_FIFO_3_ENABLE                0x13

// KEY STUFF

#define REG_BASE_UPSTREAM_KEY           DOCSIS_US_TEK000_REGISTER
#define REG_BASE_DOWNSTREAM_KEY         DOCSIS_BPI_KEY_X_0_EVEN_BASE_ADDRESS
#define REG_SIZE_UPSTREAM_KEY           0x10
#define REG_SIZE_DOWNSTREAM_KEY         0x10
#define REG_SIZE_DOWNSTREAM_SAID        0x40
#define REG_BASE_UPSTREAM_IV            DOCSIS_US_IV000_REGISTER
#define REG_BASE_DOWNSTREAM_IV          (REG_BASE_DOWNSTREAM_KEY + 0x10)
#define REG_SIZE_UPSTREAM_IV            0x10
#define REG_SIZE_DOWNSTREAM_IV          0x10


#define KILLING_TIME_ADDRESS           0x70000000


#endif
